# Generated by Django 5.2 on 2025-04-04 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryModel",
            fields=[
                (
                    "dirID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("dirName", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RepositoryModel",
            fields=[
                (
                    "repoID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("owner", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "fileID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("fileName", models.CharField(max_length=255, unique=True)),
                ("fileLink", models.CharField()),
                (
                    "directoryFk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.directorymodel",
                    ),
                ),
                (
                    "repositoryFK",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.repositorymodel",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="directorymodel",
            name="repositoryFK",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.repositorymodel"
            ),
        ),
    ]
