# Generated by Django 5.2 on 2025-04-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_directorymodel_repositorymodel_filemodel_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="directorymodel",
            table="Directories",
        ),
        migrations.AlterModelTable(
            name="filemodel",
            table="Files",
        ),
        migrations.AlterModelTable(
            name="repositorymodel",
            table="Repositories",
        ),
    ]
