# Generated by Django 5.2 on 2025-04-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_alter_directorymodel_table_alter_filemodel_table_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={},
        ),
        migrations.AlterModelTable(
            name="usermodel",
            table="Users",
        ),
    ]
