# Generated by Django 5.2 on 2025-04-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_alter_usermodel_options_alter_usermodel_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usermodel",
            table="users",
        ),
    ]
