# Generated by Django 5.2 on 2025-04-04 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0005_alter_usermodel_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorymodel",
            name="dirLink",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repositorymodel",
            name="repoLink",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="fileLink",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="UserFolders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folderLink", models.CharField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_folders",
            },
        ),
    ]
