# Generated by Django 5.2 on 2025-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0006_directorymodel_dirlink_repositorymodel_repolink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directorymodel",
            name="dirLink",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="filemodel",
            name="fileLink",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="repositorymodel",
            name="repoLink",
            field=models.CharField(),
        ),
    ]
