# Generated by Django 5.2 on 2025-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_alter_directorymodel_dirlink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="folder_link",
            field=models.CharField(blank=True, null=True),
        ),
    ]
