# Generated by Django 5.2 on 2025-04-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_rename_repositoryfk_directorymodel_repo_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="directorymodel",
            table="directories",
        ),
        migrations.AlterModelTable(
            name="filemodel",
            table="files",
        ),
        migrations.AlterModelTable(
            name="repositorymodel",
            table="repositories",
        ),
    ]
