# Generated by Django 5.2 on 2025-04-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_alter_directorymodel_table_alter_filemodel_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorymodel",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
