# Generated by Django 5.2 on 2025-04-06 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_repositorymodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorymodel",
            name="parent_dir",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.directorymodel",
            ),
        ),
        migrations.AlterField(
            model_name="repositorymodel",
            name="owner",
            field=models.CharField(blank=True, null=True),
        ),
    ]
