# Generated by Django 5.2 on 2025-04-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_directorymodel_parent_dir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directorymodel",
            name="dirName",
            field=models.CharField(default="repo_name", max_length=255),
        ),
    ]
