# Generated by Django 5.2 on 2025-04-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0014_alter_filemodel_filename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filemodel",
            old_name="repository",
            new_name="repo",
        ),
    ]
