# Generated by Django 5.2 on 2025-04-09 10:38

import django.db.models.deletion
import server.utils.uuid_generator
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_rename_repository_filemodel_repo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStorageDetails",
            fields=[
                (
                    "storageID",
                    models.CharField(
                        default=server.utils.uuid_generator.generate_short_uuid,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
