# Generated by Django 5.2 on 2025-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0017_alter_userstoragedetails_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserStorageDetails",
            new_name="UserStorageReference",
        ),
        migrations.AddField(
            model_name="directorymodel",
            name="dirLink",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="filemodel",
            name="fileLink",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="repositorymodel",
            name="repoLink",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
