# Generated by Django 5.2 on 2025-04-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0019_remove_directorymodel_dirlink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorymodel",
            name="repo_path",
            field=models.CharField(null=True),
        ),
    ]
