# Generated by Django 5.2 on 2025-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0020_repositorymodel_repo_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repositorymodel",
            name="repo_path",
            field=models.CharField(unique=True),
        ),
    ]
