# Generated by Django 5.2 on 2025-04-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0024_repositorymodel_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositorymodel",
            name="des",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
