# Generated by Django 5.2 on 2025-04-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0025_repositorymodel_des"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repositorymodel",
            old_name="name",
            new_name="repoName",
        ),
    ]
