# Generated by Django 5.2 on 2025-04-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0026_rename_name_repositorymodel_reponame"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="readme_file_link",
            field=models.CharField(default="readme.md"),
        ),
    ]
