# Generated by Django 5.2 on 2025-04-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0027_usermodel_readme_file_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="folder_link",
            new_name="folder_ref",
        ),
        migrations.RenameField(
            model_name="usermodel",
            old_name="readme_file_link",
            new_name="readme_ref",
        ),
    ]
