# Generated by Django 5.2 on 2025-04-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0028_rename_folder_link_usermodel_folder_ref_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.CharField(unique=True),
        ),
    ]
